apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
  namespace: react-app
  labels:
    app: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: docker.io/toni1997/my-react-app:1660ba5f28fa409896efd18092a63ad6cba42b74
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "200m"
              memory: "256Mi"

